### PR TITLE
Feat/start

### PR DESCRIPTION
**Pull request by pedroimpulcetto**
####  Starting Resend FastAPI Example.

Keeping the FastAPI example simple as Flask example

### CODE REVIEW

**Review by drish — APPROVED** [review]

**Comment by drish** [comment]
@pedroimpulcetto thanks for the contribution again ! im thinking of holding on on this merge til we release python sdk v2 so that we can use the "from" attribute normally.

**Comment by pedroimpulcetto** [comment]
Agree

**Comment by drish** [comment]
hey @pedroimpulcetto v2.0.0 has been released earlier today, would you to update this PR with that latest version ?

**Comment by pedroimpulcetto** [comment]
Sure! I will update to be simple as the Flask example

**Pull request merged**
